apiVersion: v1
kind: Service
metadata:
  name: demo-store-app-service
spec:
  selector:
    app:  demo-store-app-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort