apiVersion: apps/v1
kind: Deployment
metadata:
    name: demo-store-app-backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: demo-store-app-backend
    template:
        metadata:
            labels:
                app: demo-store-app-backend
        spec:
            containers:
            - name: demo-store-app
              image: matttollner/demo-store-app-backend
              imagePullPolicy: IfNotPresent
              ports:
                  - containerPort: 8080
              env:
                  - name: MYSQL_HOST
                    value: mysql
                  - name: MYSQL_USER
                    value: root
                  - name: MYSQL_PASSWORD
                    value: root


---

apiVersion: v1
kind: Service
metadata:
    name: demo-store-app-backend
spec:
    selector:
        app: demo-store-app-backend
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    type: NodePort