apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: demo-store-app-backend
spec:
  ports:
    - port: 3306
  selector:
    app: demo-store-app-backend
    tier: mysql
  clusterIP: None